const OBSGO_URL='https://qnpvqsvvsgsantekgfbz.supabase.co';
const OBSGO_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucHZxc3Z2c2dzYW50ZWtnZmJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNzg4MzIsImV4cCI6MjA5MTc1NDgzMn0.8rfv0BQpWNNSD8yrhHNwCOkcG9q5_uMD7B7z_Y324a0';
const sb=window.supabase.createClient(OBSGO_URL,OBSGO_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const MANAGEMENT_ROLES=['OWNER','TOP_MGMT','ADMIN'];
let rows=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function timeout(p,ms,label){return Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(new Error(label+' timeout')),ms))]);}
function deny(message){document.getElementById('gt').textContent='🔒 Management Access Denied';document.getElementById('gm').textContent=message;}
function normalizeVisit(r){const d=r.draft_json||{};return{who:r.created_by||r.observer||'—',dept:r.department||d.dept||'—',cls:d.classLabel||d.className||r.class_id||'—',date:r.visit_date||d.date||'',status:r.status,updated:r.updated_at||'',nStu:(d.selectedStudents||[]).length,nE:d.rows&&d.rows.ent?d.rows.ent.length:0};}
async function loadAll(){try{const x=await timeout(sb.from('obsgo_visit').select('id,created_by,created_by_uid,observer,department,class_id,visit_date,status,updated_at,draft_json').order('updated_at',{ascending:false}),10000,'Team data');if(x.error)throw x.error;rows=(x.data||[]).map(normalizeVisit);render();renderRecords();renderAnalysis();checkPlug();}catch(e){document.getElementById('progress').innerHTML='<div class="err">'+esc(e.message||e)+'</div>';}}
async function boot(){try{const s=await timeout(sb.auth.getSession(),8000,'Session');const session=s&&s.data&&s.data.session;if(!session){location.replace('https://angelteo.github.io/?returnTo='+encodeURIComponent(location.href));return;}const id=session.user&&session.user.id;if(!id)throw new Error('登入资料不完整');const m=await timeout(sb.from('users_meta').select('display_name,role,is_active').eq('user_id',id).maybeSingle(),8000,'Role check');if(m.error)throw m.error;if(!m.data||m.data.is_active===false||!MANAGEMENT_ROLES.includes(m.data.role)){deny('这个帐号没有 ObsGo Management 权限。');return;}document.getElementById('gate').style.display='none';document.getElementById('app').style.display='';await loadAll();}catch(e){deny(e&&e.message?e.message:'Management 权限检查失败。');}}
async function logout(){await sb.auth.signOut();location.replace('https://angelteo.github.io/');}
boot();