(()=>{
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let dept='ALL',cls='ALL';
function base(){return (window.rows||[]).filter(x=>(dept==='ALL'||x.dept===dept)&&(cls==='ALL'||x.cls===cls));}
function options(){const cs=[...new Set((window.rows||[]).filter(x=>dept==='ALL'||x.dept===dept).map(x=>x.cls).filter(Boolean))].sort();document.querySelectorAll('.mg-class').forEach(s=>{s.innerHTML='<option value="ALL">全部班级 / 时段</option>'+cs.map(c=>`<option>${E(c)}</option>`).join('');s.value=cs.includes(cls)?cls:'ALL';});if(!cs.includes(cls))cls='ALL';}
function bar(){return '<div class="toolbar mgbar"><select class="filter mg-dept"><option value="ALL">全部部门</option><option>SRT</option><option>SRK</option><option>ATC</option><option>GAK</option></select><select class="filter mg-class"><option value="ALL">全部班级 / 时段</option></select></div>';}
function install(){[['p-records','records'],['p-analysis','analysis']].forEach(([id,k])=>{const p=document.getElementById(id);if(p&&!p.querySelector('.mgbar'))p.querySelector('.sub').insertAdjacentHTML('afterend',bar());});const fd=document.getElementById('fdept');if(fd){fd.value=dept;fd.onchange=()=>{dept=fd.value;cls='ALL';sync();};}document.querySelectorAll('.mg-dept').forEach(s=>{s.value=dept;s.onchange=()=>{dept=s.value;cls='ALL';sync();};});document.querySelectorAll('.mg-class').forEach(s=>s.onchange=()=>{cls=s.value;sync(false);});options();}
function sync(reset=true){document.querySelectorAll('.mg-dept').forEach(s=>s.value=dept);const fd=document.getElementById('fdept');if(fd)fd.value=dept;if(reset)options();document.querySelectorAll('.mg-class').forEach(s=>s.value=cls);render();renderRecords();renderAnalysis();}
window.filtered=()=>base();
window.render=function(){install();const a=base(),draft=a.filter(x=>x.status==='draft'),done=a.filter(x=>x.status==='completed'),cancel=a.filter(x=>x.status==='cancelled'),people=new Set(a.map(x=>x.who));document.getElementById('metrics').innerHTML=`<div class="card metric"><b>${people.size}</b><span>Observers</span></div><div class="card metric"><b>${draft.length}</b><span>Open Drafts</span></div><div class="card metric"><b>${done.length}</b><span>Completed</span></div><div class="card metric"><b>${cancel.length}</b><span>Cancelled</span></div>`;const by={};a.forEach(x=>{const k=x.cls+'|'+x.who;by[k]=by[k]||{cls:x.cls,who:x.who,d:0,c:0,z:0,last:''};if(x.status==='draft')by[k].d++;if(x.status==='completed')by[k].c++;if(x.status==='cancelled')by[k].z++;if(x.updated>by[k].last)by[k].last=x.updated;});document.getElementById('progress').innerHTML='<div class="row h"><div>Class / Time</div><div>Responsible</div><div>Draft</div><div>Completed</div><div>Last Update</div></div>'+Object.values(by).sort((a,b)=>String(a.cls).localeCompare(String(b.cls))).map(v=>`<div class="row"><b>${E(v.cls)}</b><div>${E(v.who)}</div><div>${v.d}</div><div>${v.c}</div><div>${E(v.last?new Date(v.last).toLocaleString('en-GB'):'—')}</div></div>`).join('');};
window.renderRecords=function(){install();const q=((document.getElementById('q')||{}).value||'').trim().toLowerCase(),a=base().filter(x=>!q||(x.who+' '+x.dept+' '+x.cls+' '+x.date).toLowerCase().includes(q));document.getElementById('records').innerHTML='<div class="row h"><div>Class / Time</div><div>Responsible</div><div>Date</div><div>Evidence</div><div>Status</div></div>'+a.map(x=>`<div class="row"><b>${E(x.dept+' · '+x.cls)}</b><div>${E(x.who)}</div><div>${E(x.date)}</div><div>${x.nStu} students · ${x.nE} evidence</div><div>${pill(x.status)}</div></div>`).join('');};
window.renderAnalysis=function(){install();const a=base(),done=a.filter(x=>x.status==='completed').length,draft=a.filter(x=>x.status==='draft').length,cancel=a.filter(x=>x.status==='cancelled').length,total=done+draft,pct=total?Math.round(done/total*100):0;document.getElementById('analysis').innerHTML=`<div class="card metric"><b>${pct}%</b><span>Completed / active work</span></div><div class="card metric"><b>${draft}</b><span>Open Drafts</span></div><div class="card metric"><b>${done}</b><span>Completed</span></div><div class="card metric"><b>${cancel}</b><span>Cancelled</span></div>`;const by={};a.forEach(x=>{const k=x.cls+'|'+x.who;by[k]=by[k]||{cls:x.cls,who:x.who,d:0,c:0,z:0};if(x.status==='draft')by[k].d++;if(x.status==='completed')by[k].c++;if(x.status==='cancelled')by[k].z++;});document.getElementById('bydept').innerHTML='<div class="row h"><div>Class / Time</div><div>Responsible</div><div>Completed</div><div>Draft</div><div>Cancelled</div></div>'+Object.values(by).sort((a,b)=>String(a.cls).localeCompare(String(b.cls))).map(v=>`<div class="row"><b>${E(v.cls)}</b><div>${E(v.who)}</div><div>${v.c}</div><div>${v.d}</div><div>${v.z}</div></div>`).join('');};
const oldLoad=window.loadAll;window.loadAll=async function(){await oldLoad();install();sync();};
})();