(()=>{
const F={progress:{dept:'ALL',slot:'ALL',cls:'ALL'},records:{dept:'ALL',slot:'ALL',cls:'ALL'},analysis:{dept:'ALL',slot:'ALL',cls:'ALL'}};
let MASTER=[],SRTRESP={};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function rowSlot(x){const c=String(x.cls||'');const m=c.match(/(FRI\.PM|SAT\.AM|SAT\.NN|SAT\.PM)$/);return m?m[1]:'';}
function dataFor(k){const f=F[k];return rows.filter(x=>(f.dept==='ALL'||x.dept===f.dept)&&(f.slot==='ALL'||rowSlot(x)===f.slot)&&(f.cls==='ALL'||x.cls===f.cls));}
function masterFor(k){const f=F[k];return MASTER.filter(x=>(f.dept==='ALL'||x.dept===f.dept)&&(f.slot==='ALL'||x.slot===f.slot)&&(f.cls==='ALL'||x.label===f.cls));}
function slotsFor(k){const f=F[k];if(f.dept==='ALL')return[];return [...new Set(MASTER.filter(x=>x.dept===f.dept).map(x=>x.slot).filter(Boolean))].sort();}
function classesFor(k){const f=F[k];if(f.dept==='ALL')return[];return MASTER.filter(x=>x.dept===f.dept&&(f.slot==='ALL'||x.slot===f.slot)).map(x=>x.label).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true}));}
function card(label,on,fn){return `<button class="filter-card${on?' on':''}" onclick="${fn}">${E(label)}</button>`;}
function drawFilters(k){const el=document.getElementById('filters-'+k);if(!el)return;const f=F[k],ds=['ALL','SRT','SRK','ATC','GAK'];let h='<div class="filter-label">部门</div><div class="filter-cards">'+ds.map(d=>card(d==='ALL'?'全部部门':d,f.dept===d,`mgSetDept('${k}','${d}')`)).join('')+'</div>';const ss=slotsFor(k);if(ss.length){h+='<div class="filter-label second">时段</div><div class="filter-cards">'+card('全部时段',f.slot==='ALL',`mgSetSlot('${k}','ALL')`)+ss.map(s=>card(s,f.slot===s,`mgSetSlot('${k}','${s}')`)).join('')+'</div>';}const cs=classesFor(k);if(f.dept!=='ALL'&&(f.slot!=='ALL'||!ss.length)&&cs.length){h+='<div class="filter-label second">班级</div><div class="filter-cards class-cards">'+card('全部班级',f.cls==='ALL',`mgSetClass('${k}','ALL')`)+cs.map(c=>card(c,f.cls===c,`mgSetClass('${k}',${JSON.stringify(c)})`)).join('')+'</div>';}el.innerHTML=h;}
window.mgSetDept=(k,d)=>{F[k]={dept:d,slot:'ALL',cls:'ALL'};drawFilters(k);renderKey(k);};
window.mgSetSlot=(k,s)=>{F[k].slot=s;F[k].cls='ALL';drawFilters(k);renderKey(k);};
window.mgSetClass=(k,c)=>{F[k].cls=c;drawFilters(k);renderKey(k);};
function renderKey(k){if(k==='progress')render();else if(k==='records')renderRecords();else if(k==='analysis')renderAnalysis();}
function teacherFor(cls){return SRTRESP[cls]||'—';}
function observerFor(cls,a){const n=[...new Set(a.filter(x=>x.cls===cls).map(x=>x.who).filter(Boolean))];return n.length?n.join(', '):'—';}
function classUniverse(k){const m=masterFor(k).map(x=>x.label);const r=dataFor(k).map(x=>x.cls);return [...new Set([...m,...r].filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true}));}
async function loadMasters(){try{const [c,t]=await Promise.all([sb.from('hub_classes').select('dept,label,slot,level,status').eq('status','active'),sb.from('classgo_srt').select('level,slot,teacher')]);if(!c.error)MASTER=c.data||[];if(!t.error){SRTRESP={};(t.data||[]).forEach(r=>{const lv=String(r.level||'').replace(/^SRT\./,'');SRTRESP[lv+'.'+r.slot]=r.teacher||'—';});}}catch(e){console.warn('Management master data unavailable',e);}}
window.render=function(){drawFilters('progress');const a=dataFor('progress'),draft=a.filter(x=>x.status==='draft'),done=a.filter(x=>x.status==='completed'),cancel=a.filter(x=>x.status==='cancelled'),people=new Set(a.map(x=>x.who));document.getElementById('metrics').innerHTML=`<div class="card metric"><b>${people.size}</b><span>Observers</span></div><div class="card metric"><b>${draft.length}</b><span>Open Drafts</span></div><div class="card metric"><b>${done.length}</b><span>Completed</span></div><div class="card metric"><b>${cancel.length}</b><span>Cancelled</span></div>`;const vals=classUniverse('progress');document.getElementById('progress').innerHTML=vals.length?'<div class="row six h"><div>Class / Time</div><div>Responsible</div><div>Observer</div><div>Draft</div><div>Completed</div><div>Last Update</div></div>'+vals.map(cls=>{const z=a.filter(x=>x.cls===cls),d=z.filter(x=>x.status==='draft').length,c=z.filter(x=>x.status==='completed').length,last=z.map(x=>x.updated).filter(Boolean).sort().pop();return `<div class="row six"><b>${E(cls)}</b><div>${E(teacherFor(cls))}</div><div>${E(observerFor(cls,a))}</div><div>${d}</div><div>${c}</div><div>${E(last?new Date(last).toLocaleString('en-GB'):'—')}</div></div>`;}).join(''):'<div class="empty">这个范围目前没有班级资料。</div>';};
window.renderRecords=function(){drawFilters('records');const q=((document.getElementById('q')||{}).value||'').trim().toLowerCase(),a=dataFor('records').filter(x=>!q||(x.who+' '+x.dept+' '+x.cls+' '+x.date).toLowerCase().includes(q));document.getElementById('records').innerHTML=a.length?'<div class="row six h"><div>Class / Time</div><div>Responsible</div><div>Observer</div><div>Date</div><div>Evidence</div><div>Status</div></div>'+a.map(x=>`<div class="row six"><b>${E(x.dept+' · '+x.cls)}</b><div>${E(teacherFor(x.cls))}</div><div>${E(x.who)}</div><div>${E(x.date)}</div><div>${x.nStu} students · ${x.nE} evidence</div><div>${pill(x.status)}</div></div>`).join(''):'<div class="empty">这个范围目前没有巡班记录。</div>';};
window.renderAnalysis=function(){drawFilters('analysis');const a=dataFor('analysis'),done=a.filter(x=>x.status==='completed').length,draft=a.filter(x=>x.status==='draft').length,cancel=a.filter(x=>x.status==='cancelled').length,total=done+draft,pct=total?Math.round(done/total*100):0;document.getElementById('analysis').innerHTML=`<div class="card metric"><b>${pct}%</b><span>Completed / active work</span></div><div class="card metric"><b>${draft}</b><span>Open Drafts</span></div><div class="card metric"><b>${done}</b><span>Completed</span></div><div class="card metric"><b>${cancel}</b><span>Cancelled</span></div>`;const vals=classUniverse('analysis');document.getElementById('bydept').innerHTML=vals.length?'<div class="row six h"><div>Class / Time</div><div>Responsible</div><div>Observer</div><div>Completed</div><div>Draft</div><div>Cancelled</div></div>'+vals.map(cls=>{const z=a.filter(x=>x.cls===cls);return `<div class="row six"><b>${E(cls)}</b><div>${E(teacherFor(cls))}</div><div>${E(observerFor(cls,a))}</div><div>${z.filter(x=>x.status==='completed').length}</div><div>${z.filter(x=>x.status==='draft').length}</div><div>${z.filter(x=>x.status==='cancelled').length}</div></div>`;}).join(''):'<div class="empty">这个范围目前没有班级资料。</div>';};
const oldGo=window.go;window.go=function(p){oldGo(p);if(F[p])drawFilters(p);};
const oldLoad=window.loadAll;window.loadAll=async function(){await oldLoad();await loadMasters();drawFilters('progress');drawFilters('records');drawFilters('analysis');render();};
})();