(()=>{
const F={progress:{dept:'ALL',cls:'ALL'},records:{dept:'ALL',cls:'ALL'},analysis:{dept:'ALL',cls:'ALL'}};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dataFor(k){const f=F[k];return rows.filter(x=>(f.dept==='ALL'||x.dept===f.dept)&&(f.cls==='ALL'||x.cls===f.cls));}
function classesFor(k){const f=F[k];if(f.dept==='ALL')return[];return [...new Set(rows.filter(x=>x.dept===f.dept).map(x=>x.cls).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)));}
function card(label,on,fn){return `<button class="filter-card${on?' on':''}" onclick="${fn}">${E(label)}</button>`;}
function drawFilters(k){const el=document.getElementById('filters-'+k);if(!el)return;const f=F[k],ds=['ALL','SRT','SRK','ATC','GAK'];let h='<div class="filter-label">部门</div><div class="filter-cards">'+ds.map(d=>card(d==='ALL'?'全部部门':d,f.dept===d,`mgSetDept('${k}','${d}')`)).join('')+'</div>';const cs=classesFor(k);if(f.dept!=='ALL'){h+='<div class="filter-label second">班级 / 时段</div><div class="filter-cards class-cards">'+card('全部',f.cls==='ALL',`mgSetClass('${k}','ALL')`)+cs.map(c=>card(c,f.cls===c,`mgSetClass('${k}',${JSON.stringify(c)})`)).join('')+'</div>';}el.innerHTML=h;}
window.mgSetDept=(k,d)=>{F[k].dept=d;F[k].cls='ALL';drawFilters(k);renderKey(k);};
window.mgSetClass=(k,c)=>{F[k].cls=c;drawFilters(k);renderKey(k);};
function renderKey(k){if(k==='progress')render();else if(k==='records')renderRecords();else if(k==='analysis')renderAnalysis();}
window.render=function(){drawFilters('progress');const a=dataFor('progress'),draft=a.filter(x=>x.status==='draft'),done=a.filter(x=>x.status==='completed'),cancel=a.filter(x=>x.status==='cancelled'),people=new Set(a.map(x=>x.who));document.getElementById('metrics').innerHTML=`<div class="card metric"><b>${people.size}</b><span>Observers</span></div><div class="card metric"><b>${draft.length}</b><span>Open Drafts</span></div><div class="card metric"><b>${done.length}</b><span>Completed</span></div><div class="card metric"><b>${cancel.length}</b><span>Cancelled</span></div>`;const by={};a.forEach(x=>{const k=x.cls+'|'+x.who;by[k]=by[k]||{cls:x.cls,who:x.who,d:0,c:0,z:0,last:''};if(x.status==='draft')by[k].d++;if(x.status==='completed')by[k].c++;if(x.status==='cancelled')by[k].z++;if(x.updated>by[k].last)by[k].last=x.updated;});const vals=Object.values(by).sort((a,b)=>String(a.cls).localeCompare(String(b.cls))||String(a.who).localeCompare(String(b.who)));document.getElementById('progress').innerHTML=vals.length?'<div class="row h"><div>Class / Time</div><div>Responsible</div><div>Draft</div><div>Completed</div><div>Last Update</div></div>'+vals.map(v=>`<div class="row"><b>${E(v.cls)}</b><div>${E(v.who)}</div><div>${v.d}</div><div>${v.c}</div><div>${E(v.last?new Date(v.last).toLocaleString('en-GB'):'—')}</div></div>`).join(''):'<div class="empty">这个范围目前没有巡班记录。</div>';};
window.renderRecords=function(){drawFilters('records');const q=((document.getElementById('q')||{}).value||'').trim().toLowerCase(),a=dataFor('records').filter(x=>!q||(x.who+' '+x.dept+' '+x.cls+' '+x.date).toLowerCase().includes(q));document.getElementById('records').innerHTML=a.length?'<div class="row h"><div>Class / Time</div><div>Responsible</div><div>Date</div><div>Evidence</div><div>Status</div></div>'+a.map(x=>`<div class="row"><b>${E(x.dept+' · '+x.cls)}</b><div>${E(x.who)}</div><div>${E(x.date)}</div><div>${x.nStu} students · ${x.nE} evidence</div><div>${pill(x.status)}</div></div>`).join(''):'<div class="empty">这个范围目前没有巡班记录。</div>';};
window.renderAnalysis=function(){drawFilters('analysis');const a=dataFor('analysis'),done=a.filter(x=>x.status==='completed').length,draft=a.filter(x=>x.status==='draft').length,cancel=a.filter(x=>x.status==='cancelled').length,total=done+draft,pct=total?Math.round(done/total*100):0;document.getElementById('analysis').innerHTML=`<div class="card metric"><b>${pct}%</b><span>Completed / active work</span></div><div class="card metric"><b>${draft}</b><span>Open Drafts</span></div><div class="card metric"><b>${done}</b><span>Completed</span></div><div class="card metric"><b>${cancel}</b><span>Cancelled</span></div>`;const by={};a.forEach(x=>{const k=x.cls+'|'+x.who;by[k]=by[k]||{cls:x.cls,who:x.who,d:0,c:0,z:0};if(x.status==='draft')by[k].d++;if(x.status==='completed')by[k].c++;if(x.status==='cancelled')by[k].z++;});const vals=Object.values(by).sort((a,b)=>String(a.cls).localeCompare(String(b.cls))||String(a.who).localeCompare(String(b.who)));document.getElementById('bydept').innerHTML=vals.length?'<div class="row h"><div>Class / Time</div><div>Responsible</div><div>Completed</div><div>Draft</div><div>Cancelled</div></div>'+vals.map(v=>`<div class="row"><b>${E(v.cls)}</b><div>${E(v.who)}</div><div>${v.c}</div><div>${v.d}</div><div>${v.z}</div></div>`).join(''):'<div class="empty">这个范围目前没有巡班记录。</div>';};
const oldGo=window.go;window.go=function(p){oldGo(p);if(F[p])drawFilters(p);};
const oldLoad=window.loadAll;window.loadAll=async function(){await oldLoad();drawFilters('progress');drawFilters('records');drawFilters('analysis');};
})();