(()=>{
const STATE={progress:{dept:'ALL',slot:'ALL',cls:'ALL'},records:{dept:'ALL',slot:'ALL',cls:'ALL'},analysis:{dept:'ALL',slot:'ALL',cls:'ALL'}};
let catalog=[],srtTeachers=[],legacyClasses=[];
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const deptColor={SRT:'#8B6CAE',SRK:'#C45C5C',ATC:'#7AB05A',GAK:'#E8A04E'};
function normLabel(x){return String(x||'').replace(/^SRT[._-]?/,'').replace(/_/g,'.');}
function resolveVisitClass(x){if(!x)return x;const hit=legacyClasses.find(c=>String(c.id)===String(x));return hit?(hit.display_name||hit.class_name||hit.code||x):x;}
function teacherFor(c){if(!c||c.dept!=='SRT')return '';const lvl='SRT.'+String(c.level||'').replace(/^SRT\.?/,'');const hit=srtTeachers.find(t=>t.slot===c.slot&&(t.level===lvl||t.level===c.level));return hit?hit.teacher:'';}
async function loadCatalog(){try{const a=await sb.from('hub_classes').select('id,code,dept,label,slot,level,status').eq('status','active');if(!a.error)catalog=a.data||[];}catch(e){}try{const b=await sb.from('classgo_srt').select('slot,level,teacher,subj');if(!b.error)srtTeachers=b.data||[];}catch(e){}try{const c=await sb.from('classes').select('*');if(!c.error)legacyClasses=c.data||[];}catch(e){}rows.forEach(r=>{r.cls=resolveVisitClass(r.cls);});}
function allClasses(k){const s=STATE[k];return catalog.filter(c=>(s.dept==='ALL'||c.dept===s.dept)&&(s.slot==='ALL'||!c.slot||c.slot===s.slot));}
function slotsFor(k){const s=STATE[k];if(s.dept==='ALL')return[];return [...new Set(catalog.filter(c=>c.dept===s.dept&&c.slot).map(c=>c.slot))].sort();}
function classesFor(k){const s=STATE[k];if(s.dept==='ALL')return[];return allClasses(k).sort((a,b)=>String(a.label||a.code).localeCompare(String(b.label||b.code),undefined,{numeric:true}));}
function visitsFor(k){const s=STATE[k];return rows.filter(x=>(s.dept==='ALL'||x.dept===s.dept)&&(s.slot==='ALL'||String(x.cls).includes(s.slot))&&(s.cls==='ALL'||normLabel(x.cls)===normLabel(s.cls)));}
function visitStatsFor(label,k){const a=rows.filter(x=>normLabel(x.cls)===normLabel(label));return{draft:a.filter(x=>x.status==='draft').length,done:a.filter(x=>x.status==='completed').length,cancel:a.filter(x=>x.status==='cancelled').length,obs:[...new Set(a.map(x=>x.who).filter(Boolean))]};}
function mkCard(text,sub,on,attrs,color){return `<button type="button" class="mg-sel-card${on?' on':''}" ${attrs||''} style="${on&&color?'--sel:'+color:''}"><b>${E(text)}</b>${sub?`<span>${E(sub)}</span>`:''}</button>`;}
function drawSelector(k){const root=document.getElementById('filters-'+k);if(!root)return;const s=STATE[k],depts=['SRT','SRK','ATC','GAK'];let h='<div class="mg-step"><div class="mg-step-title">① 部门</div><div class="mg-option-grid">';h+=depts.map(d=>{const n=catalog.filter(c=>c.dept===d).length;return mkCard(d,n+' 班',s.dept===d,`data-k="${k}" data-type="dept" data-val="${d}"`,deptColor[d]);}).join('')+'</div></div>';
if(s.dept!=='ALL'){const slots=slotsFor(k);if(slots.length){h+='<div class="mg-step"><div class="mg-step-title">② 时段</div><div class="mg-option-grid">'+slots.map(t=>{const n=catalog.filter(c=>c.dept===s.dept&&c.slot===t).length;return mkCard(t.replace('.', ' · '),n+' 班',s.slot===t,`data-k="${k}" data-type="slot" data-val="${E(t)}"`,'#8B6C2A');}).join('')+'</div></div>';}const cs=classesFor(k);h+='<div class="mg-step"><div class="mg-step-title">③ 班级</div><div class="mg-option-grid mg-classes">'+cs.map(c=>{const label=c.label||c.code||c.id,st=visitStatsFor(label,k),teacher=teacherFor(c),parts=[];if(teacher)parts.push('负责 '+teacher);if(st.draft)parts.push(st.draft+' 未完成');if(st.done)parts.push(st.done+' 已完成');if(!st.draft&&!st.done)parts.push('未有巡班记录');return mkCard(label,parts.join(' · '),normLabel(s.cls)===normLabel(label),`data-k="${k}" data-type="cls" data-val="${E(label)}"`,deptColor[s.dept]);}).join('')+'</div></div>';}
root.innerHTML=h;root.querySelectorAll('.mg-sel-card').forEach(btn=>btn.onclick=()=>{const key=btn.dataset.k,type=btn.dataset.type,val=btn.dataset.val,st=STATE[key];if(type==='dept'){st.dept=val;st.slot='ALL';st.cls='ALL';}else if(type==='slot'){st.slot=val;st.cls='ALL';}else if(type==='cls'){st.cls=(st.cls===val?'ALL':val);}drawSelector(key);renderKey(key);});}
function renderKey(k){if(k==='progress')render();else if(k==='records')renderRecords();else renderAnalysis();}
window.render=function(){drawSelector('progress');const a=visitsFor('progress'),draft=a.filter(x=>x.status==='draft'),done=a.filter(x=>x.status==='completed'),cancel=a.filter(x=>x.status==='cancelled'),people=new Set(a.map(x=>x.who));document.getElementById('metrics').innerHTML=`<div class="card metric"><b>${people.size}</b><span>Observers</span></div><div class="card metric"><b>${draft.length}</b><span>Open Drafts</span></div><div class="card metric"><b>${done.length}</b><span>Completed</span></div><div class="card metric"><b>${cancel.length}</b><span>Cancelled</span></div>`;const s=STATE.progress;if(s.dept==='ALL'){document.getElementById('progress').innerHTML='<div class="empty">请选择一个部门查看班级进度。</div>';return;}const cs=classesFor('progress');document.getElementById('progress').innerHTML='<div class="row h six"><div>Class / Time</div><div>Responsible</div><div>Observer</div><div>Draft</div><div>Completed</div><div>Last Update</div></div>'+cs.map(c=>{const label=c.label||c.code||c.id,vs=rows.filter(x=>normLabel(x.cls)===normLabel(label)),obs=[...new Set(vs.map(x=>x.who).filter(Boolean))].join(', ')||'—',d=vs.filter(x=>x.status==='draft').length,co=vs.filter(x=>x.status==='completed').length,last=vs.map(x=>x.updated).filter(Boolean).sort().pop();return `<div class="row six"><b>${E(label)}</b><div>${E(teacherFor(c)||'—')}</div><div>${E(obs)}</div><div>${d}</div><div>${co}</div><div>${E(last?new Date(last).toLocaleString('en-GB'):'—')}</div></div>`;}).join('');};
window.renderRecords=function(){drawSelector('records');const q=((document.getElementById('q')||{}).value||'').trim().toLowerCase(),a=visitsFor('records').filter(x=>!q||(x.who+' '+x.dept+' '+x.cls+' '+x.date).toLowerCase().includes(q));document.getElementById('records').innerHTML=a.length?'<div class="row h"><div>Class / Time</div><div>Observer</div><div>Date</div><div>Evidence</div><div>Status</div></div>'+a.map(x=>`<div class="row"><b>${E(x.dept+' · '+x.cls)}</b><div>${E(x.who)}</div><div>${E(x.date)}</div><div>${x.nStu} students · ${x.nE} evidence</div><div>${pill(x.status)}</div></div>`).join(''):'<div class="empty">这个范围目前没有巡班记录。</div>';};
window.renderAnalysis=function(){drawSelector('analysis');const a=visitsFor('analysis'),done=a.filter(x=>x.status==='completed').length,draft=a.filter(x=>x.status==='draft').length,cancel=a.filter(x=>x.status==='cancelled').length,total=done+draft,pct=total?Math.round(done/total*100):0;document.getElementById('analysis').innerHTML=`<div class="card metric"><b>${pct}%</b><span>Completed / active work</span></div><div class="card metric"><b>${draft}</b><span>Open Drafts</span></div><div class="card metric"><b>${done}</b><span>Completed</span></div><div class="card metric"><b>${cancel}</b><span>Cancelled</span></div>`;const s=STATE.analysis;if(s.dept==='ALL'){document.getElementById('bydept').innerHTML='<div class="empty">请选择一个部门查看班级分析。</div>';return;}const cs=classesFor('analysis');document.getElementById('bydept').innerHTML='<div class="row h"><div>Class / Time</div><div>Responsible</div><div>Completed</div><div>Draft</div><div>Cancelled</div></div>'+cs.map(c=>{const label=c.label||c.code||c.id,vs=rows.filter(x=>normLabel(x.cls)===normLabel(label));return `<div class="row"><b>${E(label)}</b><div>${E(teacherFor(c)||'—')}</div><div>${vs.filter(x=>x.status==='completed').length}</div><div>${vs.filter(x=>x.status==='draft').length}</div><div>${vs.filter(x=>x.status==='cancelled').length}</div></div>`;}).join('');};
const oldGo=window.go;window.go=function(p){oldGo(p);if(STATE[p])drawSelector(p);};
const oldLoad=window.loadAll;window.loadAll=async function(){await oldLoad();await loadCatalog();drawSelector('progress');drawSelector('records');drawSelector('analysis');render();};
})();